[workspace]
resolver = "2"
members = ["crates/protocol", "crates/server", "crates/client-core", "crates/desktop"]

[workspace.package]
edition = "2024"
license = "MIT"

[profile.release]
opt-level = 'z'      # Optimize for size, even at the cost of some performance
strip = true         # Strip debug symbols from the binary
lto = true           # Enable Link Time Optimization (LTO)
codegen-units = 1    # Force single code generation unit for maximum optimization
panic = "abort"


