[package]
name = "octoterm-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
octoterm-protocol = { path = "../protocol" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
alacritty_terminal = "0.25"
portable-pty = "0.9"
bytes = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
